### ISSUE TITLE
cloned comfyui, win11

### ISSUE THREAD

**Issue by johnyboro** [strimmlarn/ComfyUI_Strimmlarns_aesthetic_score#1]
File "D:\AinShit\Comfy2\ComfyUI\custom_nodes\ComfyUI-Strimmlarns-Aesthetic-Score\__init__.py", line 2, in <module>
    from .my_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AinShit\Comfy2\ComfyUI\custom_nodes\ComfyUI-Strimmlarns-Aesthetic-Score\my_node.py", line 8, in <module>
    import clip
ModuleNotFoundError: No module named 'clip'

Cannot import D:\AinShit\Comfy2\ComfyUI\custom_nodes\ComfyUI-Strimmlarns-Aesthetic-Score module for custom nodes: No module named 'clip'

:(

**Comment by strimmlarn** [comment]
Yeah I realized you need clip this morning. 
If you:
1. pull/clone this repository again to update it. 
2. cd into  "ComfyUI\custom_nodes\ComfyUI-Strimmlarns-Aesthetic-Score" 
3. use  "pip install -r requirement.txt" 

or just use pip to install clip. ~~pip install clip~~  "pip install git+https://github.com/openai/CLIP.git"

It hopefully fixes it.

**Comment by johnyboro** [comment]
> Yeah I realized you need clip this morning. If you:
> 
> 1. pull/clone this repository again to update it.
> 2. cd into  "ComfyUI\custom_nodes\ComfyUI-Strimmlarns-Aesthetic-Score"
> 3. use  "pip install -r requirement.txt"
> 
> or just use pip to install clip.
> 
> It hopefully fixes it.

ty, that fixes it

**Comment by strimmlarn** [comment]
I lied now the requirements.txt instructions above this post  should work. 

"pip install clip" should be "pip install git+https://github.com/openai/CLIP.git"

**Comment by Mikerhinos** [comment]
I also get the clip and pytorch-lightning missing error, even after manually installing it on my main system Python, and also in my ComfyUI venv.

Is it incompatible with venv ?

Edit : Ok I'm just stupid, it was apparently not using the good Python path so I installed with the complete venv Python path and it's good now. Sorry for the useless necro !

**Comment by tusharbhutt** [comment]
> I also get the clip and pytorch-lightning missing error, even after manually installing it on my main system Python, and also in my ComfyUI venv.
> 
> Is it incompatible with venv ?
> 
> Edit : Ok I'm just stupid, it was apparently not using the good Python path so I installed with the complete venv Python path and it's good now. Sorry for the useless necro !

How did you manage to do that?  I get the missing pytorch-lightning error too, and I had used both commands below with no luck:

```
C:\Applications\StableDiffusion\ComfyUI\python_embeded\python.exe -s -m pip install -r requirement.txt
C:\Applications\StableDiffusion\ComfyUI\python_embeded\python.exe -s -m pip git+https://github.com/openai/CLIP.git
```
